### ISSUE TITLE
Prediction steps fail when input has more than 1 feature

### ISSUE THREAD

**Issue by minhtriet** [Willcox-Research-Group/rom-operator-inference-Python3#30]
**The objective**
Prediction when input has more than one feature

**Already tried tests**
Previously, my data has pressure as the only feature. I am trying to stack another feature as follow

$$
\begin{bmatrix} p_{1,1} & p_{1,2} & \cdots & p_{1,n} \\ 
vz_{1,1} & vz_{1,2} & \cdots & vz_{1,n} \\
 \vdots & \vdots & \vdots & \vdots \\
p_{m,1} & p_{m,2} & \cdots & p_{m,n} \\
vz_{m,1} & vz_{m,2} & \cdots & vz_{m,n} \\
\end{bmatrix} 
$$

with $vz$ as velocity in $z$ ax, $p$ as pressure. With this config, I face a this error message `/rom_operator_inference/core/nonparametric/_public.py:486: IntegrationWarning: Required step size is less than spacing between numbers.`

Code
```python
train_data_derivative = opinf.pre.ddt(data_to_train, DELTA_T, order=6)        # Calculate the time derivative matrix.
Vr, _ = opinf.pre.pod_basis(data_to_train, r=r)    
rom = opinf.ContinuousOpInfROM(modelform="cAHG") 
rom.fit(Vr, data_to_train, train_data_derivative)
prediction = rom.predict(train_data[:,-1], np.arange(0.0499, 0.0597, 1e-4))   # predict from the last column of train data
```

**Comment by shanemcq18** [comment]
Hi @minhtriet, thanks for your interest in the package. If I am reading your notation right it looks like you have the snapshot matrix (`data_to_train`) set up correctly, meaning a single column contains all variables at a fixed time. The error you are seeing comes from `scipy.integrate.solve_ivp()` and indicates that the learned reduced-order model is not stable. This could be happening for a few reasons.

- The number of POD modes `r` plays a big role in the stability of the ROM. Try with a larger or smaller `r`.
- The least-squares regression needs to be regularized. You can do this by passing the `regularizer` argument to `rom.fit()`, e.g., `rom.fit(Vr, data_to_train, train_data_derivative, regularizer=1e-2)`. Try different values for the regularizer, e.g., `1e-2`, `1e0`, `1e2`, `1e4`, etc.
- A cubic model could be overkill. See if you can get a stable linear model (`modelform="cA"`) or a stable quadratic model (`modelform="cAH"`) before you jump to a cubic model. In general, as you add terms to the model, the regularization constant needs to be increased.
- Because you are now working with multiple variables, you may need to normalized (nondimensionalize) the data first. See `opinf.pre.SnapshotTransformer`.
- As a sanity check, first try using the ROM to reconstruct the training data: that is, use the initial snapshot as the initial condition, not the last snapshot: `rom.predict(train_data[:, 0], ...)`. Your choice of normalization, number of modes, model form, and regularization can be chosen with the goal of first reproducing the training data well, then you can move on to trying to predict further in time.

We're working on more illuminating tutorials that walk through these issues. In the meantime, see [this paper](https://kiwi.oden.utexas.edu/papers/nonlinear-non-intrusive-model-reduction-combustion-McQuarrie-Huang-Willcox.pdf) for an example of a challenging application where each of these points is considered. You may be interested in [the code](https://github.com/Willcox-Research-Group/ROM-OpInf-Combustion-2D) as well.
